#include <semaphore.h>
#include <iostream>
#include <pthread.h>
#include <windows.h>
#include <stdio.h>
#include <conio.h>
#include <tchar.h>
#include <unistd.h>
#include <fcntl.h>
#include <memoryapi.h>